on:
  pull_request: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    container: node:22-alpine
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm audit --audit-level high

  test:
    runs-on: ubuntu-latest
    container: node:22-alpine
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm test
